### ISSUE TITLE
Remove obsolete "type name" concept

### ISSUE THREAD

**Issue by tabatkins** [whatwg/webidl#1131] opened 2022-04-26 18:22 UTC
I've wondered what the purpose of "type name" was in WebIDL for quite a while, because it's not actually *used* in the spec anywhere; all of the mentions are just various types defining what their type names *are*, but no mention of why they're defining them.

@annevk just tracked down the commit that it was added in:<https://github.com/whatwg/webidl/commit/8e66595d495b40d05c9926fbd01b0fa0be5ecb6a>. The *final* mention of the term in this commit reveals the purpose: it was for the old `T[]` syntax that defined `Array` subclasses; the type name was used to provide a name for the subclass in JS.

This syntax has since been removed, so it looks like we can kill the supporting infrastructure too, and remove all mentions of "type name". If this sounds good I can drop a PR for this.

**Comment by domenic** [comment] 2022-04-26 18:46
Dupe of https://github.com/whatwg/webidl/issues/835.

**Closed by domenic** 2022-04-26 18:46 UTC
