### ISSUE TITLE
Editorial: pick JavaScript or ECMAScript and stick with it

### ISSUE THREAD

**Issue by annevk** [whatwg/webidl#1313] opened 2023-06-02 08:07 UTC
We currently use both, though ECMASCript is more prevalent. I like how HTML approaches this more though (call it all JavaScript, except in the reference at the end).

**Comment by domenic** [comment] 2023-06-02 08:46
Dupe of https://github.com/whatwg/webidl/issues/863?

**Closed** 2023-06-02 09:04 UTC
