### ISSUE TITLE
Declaration of dictionaries with dynamic keys identified by type, but not by name

### ISSUE THREAD

**Issue by solomonkinard** [whatwg/webidl#1403] opened 2024-04-27 19:28 UTC
### What problem are you trying to solve?

https://github.com/whatwg/webidl/issues/1401

### Anything else?

https://github.com/whatwg/webidl/issues/1401 was opened for the creation of the appropriate Web IDL to be used to solve the problem, as evidenced by the concrete examples provided. Is there a solution to the showcased problem already available in WebIDL, and if not, how would Web IDL look for solving it?

Once a that person closed that issue, it didn't seem possible to be able to reopen it.

**Comment by petervanderbeken** [comment] 2024-04-28 13:19
Please don't file new issues just because you disagree with a decision. Domenic asked you a specific question, namely the web platform API specification that has or needs this use case. You didn't respond to that question. Without an actual concrete use case of such an API being added to an existing or new web platform specification this isn't going to be added to WebIDL. Additions and changes to WebIDL are made in response to such actual use cases.

**Comment by petervanderbeken** [comment] 2024-04-28 13:19
Duplicate of #1401.

**Closed** 2024-04-29 06:55 UTC
Labels: addition/proposal, needs implementer interest
